package com.mycast.mycastspring.controler;

import java.awt.List;
import java.util.HashMap;

import com.mycast.mycastspring.model.PodCast;
import com.mycast.mycastspring.model.PodCastRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.client.RestTemplate;





@RestController    // This means that this class is a Controller
@RequestMapping(path="/podcast" ) // This means URL's start with /demo (after Application path)
public class PodCastResource {
	@Autowired // This means to get the bean called podcastRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private PodCastRepository podcastRepository;

	@GetMapping(path="/add") // Map ONLY GET Requests
	public @ResponseBody String addNewPodcast (@RequestParam String name
			, @RequestParam boolean favorite , @RequestParam boolean history , @RequestParam boolean later , @RequestParam boolean follow) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request


		PodCast n = new PodCast();
		n.setName(name);
		n.setFavorite(favorite);
		n.setFollow(follow);
		n.setHistory(history);
		n.setLater(later);
		podcastRepository.save(n);
		return "Saved";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<PodCast> getAllUsers() {
		// This returns a JSON or XML with the users
		
		return podcastRepository.findAllFollows();
		
	}
}





// /**
//  * PodCastResource
//  */
// @RestController
// public class PodCastResource {

//     private HashMap<Integer, PodCast> podcasts;

//     public PodCastResource(){

//         this.podcasts = new HashMap<Integer, PodCast>();
        
//     }

//     @RequestMapping(value="/inicio" ,produces = MediaType.APPLICATION_JSON_VALUE , method=RequestMethod.GET)
//     public static void GetPodcastItunes(){
        
//         System.out.println("teste");
//     }
// }