CREATE TABLE PODCASTS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    podcast_name VARCHAR(250) NOT NULL,
    podcast_created_at VARCHAR(250) NOT NULL
);

CREATE TABLE EPISODES (
    id INT AUTO_INCREMENT PRIMARY KEY,
    episode_title VARCHAR(200) NOT NULL,
    episode_date DATE NOT NULL
);

CREATE TABLE USERS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_name VARCHAR(250) NOT NULL,
    birth_date date NOT NULL
);